apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
- ../shared-istio/
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/httproute.yaml
images:
- name: PROJECT/IMAGE
  newName: fallmx/log-output
  newTag: e7f3558ae20153bddf86dcd8218a8627c79f34f7
