apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/httproute.yaml
images:
- name: PROJECT/IMAGE
  newName: fallmx/log-output
  newTag: 1c13027c0a01bc30ce13ba040bd672fd0ac9c2a2
