apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
- ../shared-istio/
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/httproute.yaml
images:
- name: PROJECT/IMAGE
  newName: fallmx/log-output
  newTag: fe466e4fa4c481faa8676dfcdcce9d203b18114d
