apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-output-share
          emptyDir: {}
        - name: log-output-config
          configMap:
            name: log-output-config
            items:
            - key: "information.txt"
              path: "information.txt"
      containers:
        - name: log-output-writer
          image: PROJECT/IMAGE
          volumeMounts:
          - name: log-output-share
            mountPath: /mnt/log-output-share
          env:
          - name: ROLE
            value: writer
          - name: LOG_FILE
            value: /mnt/log-output-share/log
        - name: log-output-reader
          image: PROJECT/IMAGE
          volumeMounts:
          - name: log-output-share
            mountPath: /mnt/log-output-share
          - name: log-output-config
            mountPath: /mnt/log-output-config
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 8082
          env:
          - name: ROLE
            value: reader
          - name: LOG_FILE
            value: /mnt/log-output-share/log
          - name: FILE
            value: /mnt/log-output-config/information.txt
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: log-output-config
                key: message
          - name: PINGS_API
            value: http://ping-pong.exercises.svc.cluster.local/pings
          - name: GREETER_API
            value: http://greeter:8080
          - name: PORT
            value: "8082"
