apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-output-share
          emptyDir: {}
      containers:
        - name: log-output-writer
          image: fallmx/log-output:2.1
          volumeMounts:
          - name: log-output-share
            mountPath: /mnt/log-output-share
          env:
          - name: ROLE
            value: writer
          - name: LOG_FILE
            value: /mnt/log-output-share/log
        - name: log-output-reader
          image: fallmx/log-output:2.1
          volumeMounts:
          - name: log-output-share
            mountPath: /mnt/log-output-share
          env:
          - name: ROLE
            value: reader
          - name: LOG_FILE
            value: /mnt/log-output-share/log
          - name: PINGS_API
            value: http://ping-pong:8083/pings
          - name: PORT
            value: "8082"
