apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-output-share
          emptyDir: {}
        - name: log-and-pingpong
          persistentVolumeClaim:
            claimName: log-and-pingpong
      containers:
        - name: log-output-writer
          image: fallmx/log-output:1.11
          volumeMounts:
          - name: log-output-share
            mountPath: /mnt/log-output-share
          env:
          - name: ROLE
            value: writer
          - name: LOG_FILE
            value: /mnt/log-output-share/log
        - name: log-output-reader
          image: fallmx/log-output:1.11
          volumeMounts:
          - name: log-output-share
            mountPath: /mnt/log-output-share
          - name: log-and-pingpong
            mountPath: /mnt/log-and-pingpong
          env:
          - name: ROLE
            value: reader
          - name: LOG_FILE
            value: /mnt/log-output-share/log
          - name: PONG_FILE
            value: /mnt/log-and-pingpong/pong
          - name: PORT
            value: "8082"
