apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: ping-pong-cpu-rate-analysis
spec:
  metrics:
  - name: ping-pong-cpu-rate-analysis
    interval: 30s
    count: 11
    successCondition: result[0] < 0.1
    provider:
      prometheus:
        address: http://prom-prometheus-server.monitoring.svc.cluster.local
        query: sum(rate(container_cpu_usage_seconds_total{namespace="exercises"}[5m]))
