apiVersion: web.jaakkomo.dwk/v1
kind: DummySite
metadata:
  labels:
    app.kubernetes.io/name: dummy-site
    app.kubernetes.io/managed-by: kustomize
  name: dummysite-sample
spec:
  websiteUrl: https://en.wikipedia.org/wiki/Kubernetes
