apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-and-pingpong
spec:
  storageClassName: log-and-pingpong
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
