apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- todo-backend/
- todo-app/
- backup/
images:
  - name: PROJECT/TODO_BACKEND
    newName: fallmx/todo-backend:4.6
  - name: PROJECT/TODO_APP
    newName: fallmx/todo-app:4.5
