name: Release application

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: registry
  IMAGE_TODO_APP: todo-app
  IMAGE_TODO_BACKEND: todo-backend
  DEPLOYMENT_TODO_APP: todo-app
  DEPLOYMENT_TODO_BACKEND: todo-backend
  BRANCH: ${{ github.ref_name }}
  BASE_DOMAIN: ${{ secrets.BASE_DOMAIN }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    environment: gke
    defaults:
      run:
        working-directory: ./the-project
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.SERVICE_ACCOUNT }}"
      - name: 'Set up gcloud'
        uses: google-github-actions/setup-gcloud@v3
      - name: 'Use gcloud'
        run: gcloud info
      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v3'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'
      - name: 'Configure Docker'
        run: gcloud auth configure-docker "$REGISTRY" --quiet
      - name : 'Form the image names'
        run: |
          echo "IMAGE_TAG_TODO_APP=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_TODO_APP:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "IMAGE_TAG_TODO_BACKEND=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_TODO_BACKEND:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
      - name: Build
        run: |
          docker build --tag $IMAGE_TAG_TODO_APP ./todo-app
          docker build --tag $IMAGE_TAG_TODO_BACKEND ./todo-backend
      - name: Publish
        run: |
          docker push $IMAGE_TAG_TODO_APP
          docker push $IMAGE_TAG_TODO_BACKEND
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v3
      - name: Deploy
        run: |-
          NAMESPACE=project
          export HOSTNAME="$BASE_DOMAIN"
          if [[ "$BRANCH" != "main" ]]; then
              NAMESPACE="$BRANCH"
              export HOSTNAME="${NAMESPACE}.${BASE_DOMAIN}"
          fi
          kubectl create namespace $NAMESPACE || true
          kubectl config set-context --current --namespace=$NAMESPACE
          envsubst < ./patches/hostname.yaml.in > ./patches/hostname.yaml
          kustomize edit add patch --path ./patches/hostname.yaml
          kustomize edit set image PROJECT/TODO_APP=$IMAGE_TAG_TODO_APP
          kustomize edit set image PROJECT/TODO_BACKEND=$IMAGE_TAG_TODO_BACKEND
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment $DEPLOYMENT_TODO_BACKEND
          kubectl rollout status deployment $DEPLOYMENT_TODO_APP
          kubectl get services -o wide
