name: Deploy tagged commit to production

on:
  push:
    tags:
      - '**'

jobs:
  deploy-prod:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check images exist
        run: |
          docker manifest inspect fallmx/todo-backend:$GITHUB_SHA > /dev/null
          docker manifest inspect fallmx/todo-app:$GITHUB_SHA > /dev/null
          docker manifest inspect fallmx/broadcaster:$GITHUB_SHA > /dev/null

      - name: Checkout manifests repo
        uses: actions/checkout@v6
        with:
          repository: jaakkomo/k8s-project-manifests
          path: manifests
          token: ${{ secrets.MANIFESTS_PAT }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v3

      - name: Update production images
        working-directory: manifests/overlays/production
        run: |-
          kustomize edit set image PROJECT/TODO_BACKEND=fallmx/todo-backend:$GITHUB_SHA
          kustomize edit set image PROJECT/TODO_APP=fallmx/todo-app:$GITHUB_SHA
          kustomize edit set image PROJECT/BROADCASTER=fallmx/broadcaster:$GITHUB_SHA

      - name: Commit production deployment
        uses: EndBug/add-and-commit@v10
        with:
          cwd: manifests
          add: 'overlays/production/kustomization.yaml'
          message: Deploy tag ${{ github.ref_name }} (${{ github.sha }}) to production
