name: Build and publish the-project

on:
  push:
    branches:
      - '**'
    paths:
      - 'the-project/**'

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./the-project

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish
        run: |-
          docker build --tag "fallmx/todo-backend:$GITHUB_SHA" ./todo-backend
          docker push "fallmx/todo-backend:$GITHUB_SHA"
          docker build --tag "fallmx/todo-app:$GITHUB_SHA" ./todo-app
          docker push "fallmx/todo-app:$GITHUB_SHA"
          docker build --tag "fallmx/broadcaster:$GITHUB_SHA" ./broadcaster
          docker push "fallmx/broadcaster:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v3

      - name: Edit images in kustomization.yaml
        run: |-
          cd base
          kustomize edit set image PROJECT/TODO_BACKEND=fallmx/todo-backend:$GITHUB_SHA
          kustomize edit set image PROJECT/TODO_APP=fallmx/todo-app:$GITHUB_SHA
          kustomize edit set image PROJECT/BROADCASTER=fallmx/broadcaster:$GITHUB_SHA

      - name: Commit kustomization.yaml
        uses: EndBug/add-and-commit@v10
        with:
          add: 'the-project/base/kustomization.yaml'
          message: New version of the-project released ${{ github.sha }}
